# Still in progress
name: run-test-frontend
on: 
  push:
   branches: [main-frontend]
  pull_request: 
    branches: [main-frontend]
    
jobs:
  test:
    runs-on: [ubuntu-latest, windows-latest]
  
    steps: 
  #Checks-out the repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-node
        uses:  actions/setup-node@v4
      - name: Run the "npm run test" command
        run: npm run test
     
